# Generated by Django 3.1.2 on 2020-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(upload_to='images')),
                ('imagen2', models.ImageField(upload_to='images')),
                ('imagen3', models.ImageField(upload_to='images')),
            ],
            options={
                'ordering': ['Apellido', 'Nombre'],
            },
        ),
    ]
