# Generated by Django 3.1.2 on 2020-10-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListaPersonajes', '0004_auto_20201025_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaje',
            options={'ordering': ['Apellido', 'Nombre']},
        ),
        migrations.RenameField(
            model_name='personaje',
            old_name='first_name',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='personaje',
            old_name='last_name',
            new_name='Nombre',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='date_of_death',
        ),
    ]
