# Generated by Django 3.1.3 on 2020-11-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_auto_20201108_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['Apellido', 'Nombre', 'Username']},
        ),
    ]
