# Generated by Django 3.1.2 on 2020-11-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Ingrese su nombre', max_length=16)),
                ('Apellido', models.CharField(help_text='Ingrese su apellido', max_length=16)),
                ('Correo', models.EmailField(max_length=60)),
                ('Fecha', models.DateField()),
                ('Numero', models.CharField(help_text='+56912345678', max_length=12)),
                ('Username', models.CharField(help_text='Ingrese nombre de usuario', max_length=16)),
                ('Password', models.CharField(help_text='Ingrese su contraseña', max_length=16)),
                ('Personaje', models.CharField(choices=[(1, 'Naruto'), (2, 'Sasuke'), (3, 'Gaara'), (4, 'Itachi'), (5, 'Kakashi'), (6, 'Sakura'), (7, 'Otro')], help_text='Seleccione su personaje favorito', max_length=16)),
                ('Avatar', models.ImageField(upload_to='images')),
            ],
        ),
    ]
